name: WeTeams
main: me.devallenalt.weteams.WeTeams
version: 1.0.0
api-version: 1.20
author: dev_allenalt_tw
commands:
  team:
    description: Main team command
    usage: /team <subcommand>
    aliases: [teams, weteams]
