permissions:
  weteams.create:
    description: Allows creation of teams
    default: true
  weteams.invite:
    description: Allows inviting players to the team
    default: op
  weteams.kick:
    description: Allows kicking members from the team
    default: op
  weteams.disband:
    description: Allows disbanding the team
    default: op
  weteams.bal:
    description: Allows viewing team balance
    default: true
  weteams.chat:
    description: Allows toggling team chat
    default: true
