name: Build WeTeams Plugin

# Trigger the workflow on push to the main branch or when a pull request is opened
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # The OS where the build will run, Ubuntu is commonly used

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Java (make sure to set the Java version that works with Minecraft)
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'  # Use the appropriate version for Minecraft

    # Step 3: Cache Maven dependencies to speed up future builds
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Step 4: Build the project with Maven
    - name: Build with Maven
      run: mvn clean package --file pom.xml  # Runs Maven build command

    # Step 5: Upload the JAR file as an artifact
    - name: Upload the JAR file
      uses: actions/upload-artifact@v3
      with:
        name: weteams-plugin
        path: target/WeTeams-1.0.0.jar  # Path to your output .jar file
